version: '3.8'

services:
  cache-db:
    image: redis:6.2.5
    container_name: parsing_cache
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "-a", "crisda24", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      --requirepass crisda24 --port 6379