spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: parsing-files-apache-camel
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #data:
  redis:
    host: localhost
    port: 6379
    password: 'crisda24'
    timeout: 20000
    database: 0

  logging:
    level:
      org.springframework.r2dbc.core: DEBUG
      org.apache.camel: DEBUG
      org.apache.camel.component.redis: DEBUG

  r2dbc:
    url: r2dbc:mssql://localhost:1433/SampleDB
    username: sa
    password: StrongPassword123
    driver: sqlserver